# Generated by Django 5.1.4 on 2025-01-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_post_main_post_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
